services:
  - type: web
    name: theater-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    restartPolicy: always
    environmentVariables:
      - key: TELEGRAM_TOKEN
        valueFrom: 
          secretKeyRef: 
            name: telegram-bot-token
    healthCheck:
      path: /health
      interval: 30s
      timeout: 5s
      retries: 3
      initialDelay: 60s
